import './globals.css';
import type { Metadata } from 'next';
import { Inter, IM_Fell_French_Canon } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });
const imFellFrenchCanon = IM_Fell_French_Canon({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${imFellFrenchCanon.className}`}>{children}</body>
    </html>
  );
}
